terraform-google-modules/terraform-google-vm

- modules/mig/outputs.tf
Added instance_group to outputs. This is needed by load balancers so will be useful when using with terraform LB module with MIG as a backend.
> added instance_group to outputs

- modules/instance_template/main.tf
- modules/instance_template/variables.tf
I noticed the preemptible argument was missed on the original 0.12 branch as I was reviewing the CHANGELOG for release.
> Update preemptible argument for Terraform 0.12

- CHANGELOG.md
- README.md
- modules/mig/main.tf
- modules/mig_with_percent/main.tf
Fixes #28
Highlight:
```
~ distribution_policy_zones = [
- "europe-west3-a",
- "europe-west3-b",
- "europe-west3-c",
] -> (known after apply) # forces replacement
```
ignore using **lifecycle**
> issue #28 - RegionInstanceGroupManager is forced to be re-created - fix.

- modules/mig/main.tf
Currently if we work in a specific region we'll have to specify it in our google provider.
This change allows to keep a region-agnostic provider and simply pass the region to the `data.google_compute_zones.available` resource.
> Allow setting region without updating provider

- README.md
- modules/mig/main.tf
- modules/mig_with_percent/main.tf
I enabled autoscaling on the module and noticed that it required the region field as well.
> Region fix

- modules/mig/main.tf
Terraform 12 does not require Quotes on some variables throwing "Warning: Quoted references are deprecated"
> Removing "Warning: Quoted references are deprecated"

- examples/compute_instance/simple/README.md
- examples/compute_instance/simple/main.tf
- examples/compute_instance/simple/variables.tf
- modules/compute_instance/main.tf
- test/fixtures/compute_instance/simple/main.tf
fixes #60 
- Instance template self link is of the form `https://www.googleapis.com/compute/beta/projects/project-name/../../... `Use regex to extract _{project-name}_; if not found fall back to provider level project id
> Derive Project id for instance from instance template

- autogen/main.tf.tmpl
- autogen/versions.tf
- examples/compute_instance/simple/main.tf
- examples/instance_template/additional_disks/main.tf
- examples/instance_template/simple/main.tf
- examples/mig/autoscaler/main.tf
- examples/mig/full/main.tf
- examples/mig/simple/main.tf
- examples/mig_with_percent/simple/README.md
- examples/mig_with_percent/simple/main.tf
- examples/mig_with_percent/simple/outputs.tf
- examples/preemptible_and_regular_instance_templates/simple/main.tf
- examples/umig/full/main.tf
- examples/umig/named_ports/main.tf
- examples/umig/simple/main.tf
- examples/umig/static_ips/main.tf
- modules/compute_instance/versions.tf
- modules/instance_template/versions.tf
- modules/mig/versions.tf
- modules/mig_with_percent/versions.tf
- modules/umig/versions.tf
- test/setup/main.tf
- Modules: Upgrade allowed Google provider from ~>2.7 to ">=2.7, <4.0"
- Examples: Passed from ~>2.x to ~>3.0
- 2 outputs added to the mig_with_percent example, to correct a failing test (because the instances were "about to be created" when tested)
- main.tf template modified to pass the lint tests
ran:
- examples individually
- integration tests
- generate_modules
- generate_docs
- test_lint
Please don't hesitate if I missed something or if it should be done differently
> Allow the use of Google provider v3.x

- examples/compute_instance/simple/README.md
- examples/compute_instance/simple/main.tf
- examples/compute_instance/simple/variables.tf
- modules/compute_instance/README.md
- modules/compute_instance/main.tf
- modules/compute_instance/variables.tf
- include examples
- dynamic and static address
- update readme
> Add public IP support

- autogen/main.tf.tmpl
- autogen/variables.tf.tmpl
- examples/mig/full/variables.tf
- modules/mig/README.md
- modules/mig/main.tf
- modules/mig/variables.tf
- modules/mig_with_percent/README.md
- modules/mig_with_percent/main.tf
- modules/mig_with_percent/variables.tf
* Updated: wait_for_instances variable, autogen docs
* Updated: Added missing autogen doc for stateful_disks
> feat: Add wait_for_instances support for mig (#95)

- examples/umig/full/main.tf
- modules/umig/main.tf
- modules/umig/variables.tf
**Problem:**
Currently it is not possible to have multiple instances with predefined access configs (external ips). If one would want to create 3 instances with 3 external ips, each instance would get same 3 predefined external ips. Which is not possible. 
**Solution:**
Make `access_config` 2D array, so each instance would get an array of predefined ips.
> fix(UMIG): access_config should be 2D array

- Makefile
- autogen/outputs.tf.tmpl
- build/int.cloudbuild.yaml
- build/lint.cloudbuild.yaml
- examples/compute_instance/simple/README.md
- examples/instance_template/additional_disks/README.md
- examples/instance_template/simple/README.md
- examples/mig/autoscaler/README.md
- examples/mig/simple/README.md
- examples/mig_with_percent/simple/README.md
- examples/preemptible_and_regular_instance_templates/simple/README.md
- examples/umig/named_ports/README.md
- examples/umig/simple/README.md
- examples/umig/static_ips/README.md
- modules/compute_instance/README.md
- modules/instance_template/README.md
- modules/mig/README.md
- modules/mig/outputs.tf
- modules/mig_with_percent/README.md
- modules/mig_with_percent/outputs.tf
- modules/preemptible_and_regular_instance_templates/README.md
- modules/umig/README.md
This change adds an output of the health_check.
Without this output, one has to conventionally construct a self-link when consumed by a `google_compute_region_backend_service`. This gives a simpler way to connect that resource with this module.
> adds an output for the health check self_links to be consumed by load balancer resources outside this module

- modules/instance_template/main.tf
This PR fixes #125.
The reason behind using CentOS 7 over newer CentOS 8 is that the latest version is still not that widely adopted and defaults to an environment that may suit fewer people overall.
> feat!: Update default source image and family to latest CentOS 7.

- autogen/main.tf.tmpl
- autogen/variables.tf.tmpl
- modules/mig/README.md
- modules/mig/main.tf
- modules/mig/variables.tf
- modules/mig_with_percent/README.md
- modules/mig_with_percent/main.tf
- modules/mig_with_percent/variables.tf
This allows for overriding the mig name which allows for multiple migs with the same hostname. And also allows for the use case of #87 Where they want the instances to have a different name than the mig.
Fixes #87 
Signed-off-by: Taylor Jones <taylor@tjon.es>
> feat: Allow Overriding MIG name (terraform-google-modules#87)

- modules/instance_template/README.md
- modules/instance_template/variables.tf
- modules/mig/versions.tf
- modules/mig_with_percent/versions.tf
"gce-uefi-images" is being deprecated (ubuntu image has been removed from the project). As Shielded VM is by default now, users can just use images from their default prod image project.
sudo make build
sudo make docker_test_lint
> Change GCE image project as "gce-uefi-images" is being deprecated.

- modules/instance_template/main.tf
This should solve the need for `local-ssd` disk types.
I tested it with:
```
additional_disks = [
{
disk_name = ""
device_name = ""
auto_delete = "true"
boot = "false"
disk_type = "local-ssd"
disk_size_gb = "375"
},
{
disk_name = ""
device_name = ""
auto_delete = "true"
boot = "false"
disk_type = "local-ssd"
disk_size_gb = "375"
}
]
```
I saw other approaches in #138 #75 and based on those I tried this approach which considers:
- It will not be a breaking change.
- It fixes some settings like `disk_size_gb=375Gb` and `type=SCRATCH` but those can't be changed anyway when working with `local-ssd` disks (AFAIK).
- The only caveat I can think about is that the disk `interface` will be fixed for all the `local-ssd` disks you define (Instead of a per disk) but I think it is somewhat acceptable …
> Add support for local-ssd disks

- modules/instance_template/README.md
- modules/instance_template/main.tf
- modules/instance_template/variables.tf
Fixes https://github.com/terraform-google-modules/terraform-google-vm/issues/130
Add support for conf. compute instances.  
Currently the conf compute flags are in googe-beta and i've tested it locally by overriding the provider block in the template defnition:
- modules/instance_template/main.tf`
```hcl
resource "google_compute_instance_template" "tpl" {
provider = google-beta
name_prefix             = "${var.name_prefix}-"
project                 = var.project_id
```
---
with the config:
- `https://github.com/terraform-google-modules/terraform-google-vm/blob/master/examples/compute_instance/simple/main.tf`
```hcl
provider "google" {}
module "instance_template" {
source          = "../../../modules/instance_template"
region          = var.region
project_id      = var.project_id …
```
> Add confidential compute flags

- modules/instance_template/README.md
- modules/instance_template/main.tf
- modules/instance_template/variables.tf
- Current `inputs` for the `instance_template` module does not support the `min_cpu_platform` attribute; however this is supported in the [`google_compute_instance_template`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template#min_cpu_platform) used by the module itself.
- Add support for `min_cpu_platform`.
-  Noticed this stale [PR#102](https://github.com/terraform-google-modules/terraform-google-vm/pull/102) opened some ago; both do the same thing
- PR opened in part to support the effort to enable AnthosBM installation using Terraform [(PR#11 of Anthos Samples)](https://github.com/GoogleCloudPlatform/anthos-samples/pull/11)
> feat: Add support for min_cpu_platform variable

- modules/instance_template/README.md
- modules/instance_template/main.tf
- modules/instance_template/variables.tf
- Current `inputs` for the `instance_template` module does not support associating a GPU to the template; however this is supported in the [`google_compute_instance_template`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template#guest_accelerator) used by the module itself.
- Add support for associating a GPU to the template by adding a new input variable `gpu` to module.
- We internally use the already existing `guest_accelerator` variable of `google_compute_instance_template` 
- PR opened in part to support the effort to enable AnthosBM installation using Terraform [(PR#11 of Anthos Samples)](https://github.com/GoogleCloudPlatform/anthos-samples/pull/11)
- Related [issue](https://github.com/GoogleCloudPlatform/anthos-samples/issues/12) …
> Add support for guest_accelerator for the instance_template module

- examples/compute_instance/disk_snapshot/main.tf
- examples/instance_template/additional_disks/main.tf
- examples/mig/full/main.tf
- examples/mig/full/variables.tf
- examples/umig/full/variables.tf
- modules/instance_template/README.md
- modules/instance_template/main.tf
- modules/instance_template/variables.tf
- modules/preemptible_and_regular_instance_templates/README.md
- modules/preemptible_and_regular_instance_templates/variables.tf
Disk attached to instances created to a template does not assign labels to it. This changes allow labels to be set to boot and additional disks of instance templates.
This PR might fix #167
> Adds labels to boot and additional disks

- modules/compute_instance/outputs.tf
- This PR reverts the change in PR #164 
- That PR was opened in response to issue #163 
- Issue #163 was due to bugs specific to changes on `sensitive` flag in terraform `v15.0.0` 
- https://github.com/hashicorp/terraform/pull/28442
- https://github.com/hashicorp/terraform/pull/28383
- https://github.com/hashicorp/terraform/pull/28472
- All these bugs were fixed in terraform `v0.15.0.1` - [Release notes](https://github.com/hashicorp/terraform/releases/tag/v0.15.1)
- Having this field as **sensitive** prevents using the attributes of the `instance_details` output in any other terraform script. (e.g: [anthos-samples use case](https://github.com/GoogleCloudPlatform/anthos-samples/blob/master/anthos-bm-gcp-terraform/modules/vm/outputs.tf#L21))
- The originally reported issue is evaded since …
> fix: revert change related to sensitive field bug in terraform 0.15.0

- build/int.cloudbuild.yaml
similar to https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/965
Running init concurrently can cause errors as the multiple TF processes would try to populate the shared cache. When running init in serial, the first test populates its providers, second test reuses existing + downloads any new providers needed
> chore: serial init for build

- examples/compute_instance/simple/README.md
- examples/compute_instance/simple/main.tf
- examples/compute_instance/simple/variables.tf
- modules/compute_instance/README.md
- modules/compute_instance/main.tf
- modules/compute_instance/variables.tf
This PR adds a new variable `deletion_protection` to the sub module `compute_instance`, which allows you to enable deletion protection on instances:
https://cloud.google.com/compute/docs/instances/preventing-accidental-vm-deletion
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance
> [compute_instance] Add deletion_protection variable

- examples/instance_template/simple/README.md
- examples/instance_template/simple/main.tf
- examples/instance_template/simple/variables.tf
- modules/instance_template/README.md
- modules/instance_template/main.tf
- modules/instance_template/variables.tf
Allow creation of instance templates that either have nested virtualization enabled or support SMT.
> Add advanced machine feature options

- modules/compute_instance/main.tf
There seemed to have been no method of using the network as configured in the template, which actually allows more configuration than the compute_instance module itself. I'm not entirely sure if this is the correct way to do it, but it does seem logical to me.
I might need some help with the code checks, as `make docker_test_lint` exited with and error, but it only showed validation warnings and no errors, so I'm a bit confused about what I'm missing here.
> Use network settings from template when no specific override is in place

- modules/instance_template/main.tf
- The `service_account` variable for the `instant_template` module is a *required* variable
- This variable is used as part of the content section of the dynamic block for the `google_compute_instance_template` resource from the provider
- Thus, it is not possible to create an instant template with no service account associated with it
- As a result it's not possible to go from the `instant_template` module in this repo to a GCE VM which has no service account associated with it
- This is friction full in certain use-cases; for example when installing Anthos bare metal on GCE VMs that have a Service Account associated with it; there are some parts of the install that conflict with this service account
- Thus we want to be able to create instance_templates which has no service account …
> improvement: allow null service_account

- examples/instance_template/simple/README.md
- examples/instance_template/simple/main.tf
- examples/instance_template/simple/variables.tf
- modules/instance_template/README.md
- modules/instance_template/variables.tf
> fix: change stack_type for better upgrade compat

- modules/instance_template/README.md
- modules/instance_template/main.tf
- modules/instance_template/variables.tf
- modules/umig/README.md
This PR adds support to specify the NIC type of the primary network interface for instance templates. This field is important VM families and operating systems that support GVNIC and get increased network performance. It defaults to null, the current behavior (unspecified), so this is not a change that requires user action. `var.additional_networks` supports this field, but the primary interface does not.
I can eventually see a breaking change where `var.additional_networks` becomes `var.networks` (or var.network_interfaces) and the primary network interface is inferred from the 1st element in the list. This would eliminate functionality gaps between the primary interface and secondary interfaces.
> feat: support setting nic_type of primary network interface

- modules/instance_template/variables.tf
Although supplying incompatible network and subnetworks will not work, it is not strictly required to supply just one or the other; we should not introduce this change in behavior in 10.0 on a field that existed in 9.0.
This validation block makes more sense in the [HPC Toolkit])(github.com/GoogleCloudPlatform), where I copied it from, but I don't think it belongs in the more general CFT modules.
Follow-up to #330.
> fix: remove unnecessary validation block

- modules/instance_template/README.md
- modules/instance_template/main.tf
- modules/instance_template/metadata.yaml
- modules/instance_template/variables.tf
Adds `resource_policies` to disk to enable the use of automatic snapshot creations.
```
resource_policies: A list (short name or id) of resource policies to attach to this disk for automatic snapshot creations.
Currently a max of 1 resource policy is supported.
```
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template
> feat: add disk resource policies

- examples/confidential_computing/README.md
- examples/confidential_computing/org_policies.tf
- test/integration/confidential_compute_instance/confidential_compute_instance_test.go
- test/setup/iam.tf
This PR adds org policies to the existing confidential computing example.
> feat: add org policies to confidential computing example

- modules/instance_template/metadata.yaml
When connection to pubsub is created:
* Add `TOPIC_ID` metadata variable
* Grant `roles/pubsub.publisher`, `roles/pubsub.subscriber` roles for specified project
> chore: add pubsub connection metadata

- modules/instance_template/metadata.yaml
Adding bigtable connection metadata. Bigtable outputs can be verified at https://github.com/GoogleCloudPlatform/terraform-google-bigtable/blob/main/outputs.tf.
> chore: Add bigtable connection metadata

- Makefile
- metadata.display.yaml
- modules/compute_disk_snapshot/metadata.display.yaml
- modules/compute_disk_snapshot/metadata.yaml
- modules/compute_disk_snapshot/versions.tf
- modules/compute_instance/metadata.display.yaml
- modules/compute_instance/metadata.yaml
- modules/compute_instance/versions.tf
- modules/instance_template/README.md
- modules/instance_template/main.tf
- modules/instance_template/metadata.display.yaml
- modules/instance_template/metadata.yaml
- modules/instance_template/variables.tf
- modules/instance_template/versions.tf
- modules/mig/metadata.yaml
- modules/mig_with_percent/metadata.display.yaml
- modules/preemptible_and_regular_instance_templates/metadata.display.yaml
- modules/preemptible_and_regular_instance_templates/metadata.yaml
- modules/preemptible_and_regular_instance_templates/versions.tf
- modules/umig/metadata.display.yaml
- modules/umig/metadata.yaml
- modules/umig/versions.tf
> feat: added resource_manager_tags in instance_template sub-module

- Makefile
- metadata.yaml
- modules/compute_disk_snapshot/metadata.yaml
- modules/compute_instance/metadata.yaml
- modules/instance_template/metadata.yaml
- modules/mig/metadata.yaml
- modules/mig_with_percent/metadata.yaml
- modules/preemptible_and_regular_instance_templates/metadata.yaml
- modules/umig/metadata.yaml
- test/setup/iam.tf
- test/setup/main.tf
Introduced:
- per_module_roles: to config required roles to run each sub modules.
- per_module_service: to config required services to run each sub modules.
Added feature flag `--per-module-requirements` to generate_docs cmd, to align with the per module configs.
> feat: per module requirements configs to vm
